export default {
    MODEL_TYPES:{
        PAGING:{
            TYPE:"paging"
        },
        PRODUCT_LIST:{
            TYPE:"productlist"
        },
        PRODUCT_ITEM:{
            TYPE:"productitem"
        },
        SUMMARY:{
            TYPE:"summary"
        },
        EMPTY:{
            TYPE:"empty"
        }
    }
}